[package]
name = "example"
version = "1.0.0"

[[bin]]
default = true
bin_name = "default"

[bin.args]
linker_args = "-shared"
out_path = "./target/lib/"
out_name = "${name}-${version}.so"

[bin.compiling]
before = ["mkdir -p ./target/lib ./target/obj"]
