[package]
name = "example"
version = "1.0.0"

[tools]
compiler = "clang"
linker = "mold"

[meta]
src_files = "find ./src/* -name \"*.c\""
header_dirs = "find ./src/include/* -type d"
obj_files = "find ./target/obj/* -name \"*.o\""

[compile]
before = [ 
	"mkdir -p ./target/obj",
	"mkdir -p ./target/bin",
]
run = [ 
	"${compiler} -c ${src_files} -I ${header_dirs}",
	"mv *.o target/obj",
]

[linking]
run = [ 
	"${compiler} -B ${linker} ${obj_files} -o ./target/bin/${name}-${version}"
]
after = [
	# clean up
	"rm -rf ./target/obj" 
]
