[package]
name = "example"
version = "1.0.0"

# this is a fully filled out toml

[meta]
src_files = "find ./src/ -name \"*.c\""       # optional
header_dirs = "find ./src/include -type d"    # optional
obj_files = "find ./result/obj -name \"*.o\"" # optional
compiler_args = "-O2 -Wpedantic"              # optional
linker_args = ""                              # optional
output_name = "./result/bin/{name}-{version}" # optional

[tools]
compiler = "clang" # optional
linker = "mold"    # optional

[compile]
before = ["mkdir -p /target/bin", "mkdir -p /target/obj"] # optional
run = [
	"${compiler} ${compiler_args} -c ${src_files} -I ${header_dirs}",
] # optional
after = ["mv *.o target/obj"] # optional

[linking]
before = [] # optional
run = [
	"${compiler} ${linker_args} -B ${linker} ${obj_files} -o ${output_name}",
] # optional
after = ["rm -rf ./target/obj"] # optional
